/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Destination = IDL.Variant({
  'usa' : IDL.Null,
  'europe' : IDL.Null,
  'asia' : IDL.Null,
  'thailand' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'challenging' : IDL.Null,
  'expert' : IDL.Null,
  'moderate' : IDL.Null,
});
export const ItineraryDay = IDL.Record({
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Tour = IDL.Record({
  'id' : IDL.Nat,
  'destination' : Destination,
  'duration' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'tourDates' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'maxGroupSize' : IDL.Nat,
  'highlights' : IDL.Vec(IDL.Text),
  'shortDescription' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'fullDescription' : IDL.Text,
  'priceUSD' : IDL.Nat,
  'itinerary' : IDL.Vec(ItineraryDay),
  'route' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'submittedAt' : IDL.Text,
  'email' : IDL.Text,
  'tourInterest' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'chatId' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'tourName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const InquiryInput = IDL.Record({
  'email' : IDL.Text,
  'tourInterest' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'chatId' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getFeaturedTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTour' : IDL.Func([IDL.Nat], [Tour], ['query']),
  'getTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'getToursByDestination' : IDL.Func([Destination], [IDL.Vec(Tour)], ['query']),
  'submitInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Destination = IDL.Variant({
    'usa' : IDL.Null,
    'europe' : IDL.Null,
    'asia' : IDL.Null,
    'thailand' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'challenging' : IDL.Null,
    'expert' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const ItineraryDay = IDL.Record({
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Tour = IDL.Record({
    'id' : IDL.Nat,
    'destination' : Destination,
    'duration' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'tourDates' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'maxGroupSize' : IDL.Nat,
    'highlights' : IDL.Vec(IDL.Text),
    'shortDescription' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'fullDescription' : IDL.Text,
    'priceUSD' : IDL.Nat,
    'itinerary' : IDL.Vec(ItineraryDay),
    'route' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'submittedAt' : IDL.Text,
    'email' : IDL.Text,
    'tourInterest' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'chatId' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'tourName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const InquiryInput = IDL.Record({
    'email' : IDL.Text,
    'tourInterest' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'chatId' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'getFeaturedTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTour' : IDL.Func([IDL.Nat], [Tour], ['query']),
    'getTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'getToursByDestination' : IDL.Func(
        [Destination],
        [IDL.Vec(Tour)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };