/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Destination = { 'usa' : null } |
  { 'europe' : null } |
  { 'asia' : null } |
  { 'thailand' : null };
export type Difficulty = { 'easy' : null } |
  { 'challenging' : null } |
  { 'expert' : null } |
  { 'moderate' : null };
export interface Inquiry {
  'id' : bigint,
  'submittedAt' : string,
  'email' : string,
  'tourInterest' : [] | [string],
  'message' : string,
  'chatId' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface InquiryInput {
  'email' : string,
  'tourInterest' : [] | [string],
  'message' : string,
  'chatId' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface ItineraryDay {
  'day' : bigint,
  'title' : string,
  'description' : string,
}
export interface Testimonial {
  'id' : bigint,
  'country' : string,
  'date' : string,
  'name' : string,
  'text' : string,
  'tourName' : string,
  'rating' : bigint,
}
export interface Tour {
  'id' : bigint,
  'destination' : Destination,
  'duration' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'tourDates' : Array<string>,
  'isActive' : boolean,
  'maxGroupSize' : bigint,
  'highlights' : Array<string>,
  'shortDescription' : string,
  'isFeatured' : boolean,
  'fullDescription' : string,
  'priceUSD' : bigint,
  'itinerary' : Array<ItineraryDay>,
  'route' : string,
}
export interface _SERVICE {
  'getFeaturedTours' : ActorMethod<[], Array<Tour>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTour' : ActorMethod<[bigint], Tour>,
  'getTours' : ActorMethod<[], Array<Tour>>,
  'getToursByDestination' : ActorMethod<[Destination], Array<Tour>>,
  'submitInquiry' : ActorMethod<[InquiryInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];