/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ItineraryDay {
    day: bigint;
    title: string;
    description: string;
}
export interface Tour {
    id: bigint;
    destination: Destination;
    duration: bigint;
    difficulty: Difficulty;
    name: string;
    tourDates: Array<string>;
    isActive: boolean;
    maxGroupSize: bigint;
    highlights: Array<string>;
    shortDescription: string;
    isFeatured: boolean;
    fullDescription: string;
    priceUSD: bigint;
    itinerary: Array<ItineraryDay>;
    route: string;
}
export interface InquiryInput {
    email: string;
    tourInterest?: string;
    message: string;
    chatId: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface Inquiry {
    id: bigint;
    submittedAt: string;
    email: string;
    tourInterest?: string;
    message: string;
    chatId: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface Testimonial {
    id: bigint;
    country: string;
    date: string;
    name: string;
    text: string;
    tourName: string;
    rating: bigint;
}
export enum Destination {
    usa = "usa",
    europe = "europe",
    asia = "asia",
    thailand = "thailand"
}
export enum Difficulty {
    easy = "easy",
    challenging = "challenging",
    expert = "expert",
    moderate = "moderate"
}
export interface backendInterface {
    getFeaturedTours(): Promise<Array<Tour>>;
    getInquiries(): Promise<Array<Inquiry>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getTour(id: bigint): Promise<Tour>;
    getTours(): Promise<Array<Tour>>;
    getToursByDestination(destination: Destination): Promise<Array<Tour>>;
    submitInquiry(input: InquiryInput): Promise<bigint>;
}
import type { Destination as _Destination, Difficulty as _Difficulty, Inquiry as _Inquiry, InquiryInput as _InquiryInput, ItineraryDay as _ItineraryDay, Tour as _Tour } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getFeaturedTours(): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedTours();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedTours();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getTour(arg0: bigint): Promise<Tour> {
        if (this.processError) {
            try {
                const result = await this.actor.getTour(arg0);
                return from_candid_Tour_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTour(arg0);
            return from_candid_Tour_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTours(): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTours();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTours();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToursByDestination(arg0: Destination): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToursByDestination(to_candid_Destination_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToursByDestination(to_candid_Destination_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: InquiryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(to_candid_InquiryInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(to_candid_InquiryInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Destination_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Destination): Destination {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Tour_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tour): Tour {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    submittedAt: string;
    email: string;
    tourInterest: [] | [string];
    message: string;
    chatId: string;
    phone: string;
    lastName: string;
    firstName: string;
}): {
    id: bigint;
    submittedAt: string;
    email: string;
    tourInterest?: string;
    message: string;
    chatId: string;
    phone: string;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        submittedAt: value.submittedAt,
        email: value.email,
        tourInterest: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.tourInterest)),
        message: value.message,
        chatId: value.chatId,
        phone: value.phone,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    destination: _Destination;
    duration: bigint;
    difficulty: _Difficulty;
    name: string;
    tourDates: Array<string>;
    isActive: boolean;
    maxGroupSize: bigint;
    highlights: Array<string>;
    shortDescription: string;
    isFeatured: boolean;
    fullDescription: string;
    priceUSD: bigint;
    itinerary: Array<_ItineraryDay>;
    route: string;
}): {
    id: bigint;
    destination: Destination;
    duration: bigint;
    difficulty: Difficulty;
    name: string;
    tourDates: Array<string>;
    isActive: boolean;
    maxGroupSize: bigint;
    highlights: Array<string>;
    shortDescription: string;
    isFeatured: boolean;
    fullDescription: string;
    priceUSD: bigint;
    itinerary: Array<ItineraryDay>;
    route: string;
} {
    return {
        id: value.id,
        destination: from_candid_Destination_n4(_uploadFile, _downloadFile, value.destination),
        duration: value.duration,
        difficulty: from_candid_Difficulty_n6(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        tourDates: value.tourDates,
        isActive: value.isActive,
        maxGroupSize: value.maxGroupSize,
        highlights: value.highlights,
        shortDescription: value.shortDescription,
        isFeatured: value.isFeatured,
        fullDescription: value.fullDescription,
        priceUSD: value.priceUSD,
        itinerary: value.itinerary,
        route: value.route
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usa: null;
} | {
    europe: null;
} | {
    asia: null;
} | {
    thailand: null;
}): Destination {
    return "usa" in value ? Destination.usa : "europe" in value ? Destination.europe : "asia" in value ? Destination.asia : "thailand" in value ? Destination.thailand : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    challenging: null;
} | {
    expert: null;
} | {
    moderate: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "challenging" in value ? Difficulty.challenging : "expert" in value ? Difficulty.expert : "moderate" in value ? Difficulty.moderate : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tour>): Array<Tour> {
    return value.map((x)=>from_candid_Tour_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Destination_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Destination): _Destination {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryInput): _InquiryInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
    tourInterest?: string;
    message: string;
    chatId: string;
    phone: string;
    lastName: string;
    firstName: string;
}): {
    email: string;
    tourInterest: [] | [string];
    message: string;
    chatId: string;
    phone: string;
    lastName: string;
    firstName: string;
} {
    return {
        email: value.email,
        tourInterest: value.tourInterest ? candid_some(value.tourInterest) : candid_none(),
        message: value.message,
        chatId: value.chatId,
        phone: value.phone,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Destination): {
    usa: null;
} | {
    europe: null;
} | {
    asia: null;
} | {
    thailand: null;
} {
    return value == Destination.usa ? {
        usa: null
    } : value == Destination.europe ? {
        europe: null
    } : value == Destination.asia ? {
        asia: null
    } : value == Destination.thailand ? {
        thailand: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
